name: Deploy Basic
on:
  workflow_dispatch:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create SSH_PRIVATE_KEY
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/private-key.pem
          chmod 600 ~/private-key.pem
          
      - name: Create SSH Directory
        run: |
          mkdir -p ~/.ssh

      - name: Add host
        run: |
          ssh-keyscan ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Copy Repository Files to Remote Server
        run: |
          cd ${{ github.workspace }}
          scp -i ~/private-key.pem -r ./* ${{ secrets.USER }}@${{ secrets.HOST }}:/home/${{ secrets.USER }}
          echo "Copied Repository Files"
        
